### ISSUE TITLE
How can we compile on arm64 arch

### ISSUE THREAD

**Issue by woshiyyya** [4kills/zlib#10]
When I tried to build my go project on arm64 Ubuntu 18.04, it failed to build and the error message is:

```
# github.com/4kills/go-zlib/native
/usr/bin/ld: ../../../go/pkg/mod/github.com/4kills/go-zlib@v1.1.0/native/libs/linuxlibz.a(deflate.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../../../go/pkg/mod/github.com/4kills/go-zlib@v1.1.0/native/libs/linuxlibz.a(deflate.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../../../go/pkg/mod/github.com/4kills/go-zlib@v1.1.0/native/libs/linuxlibz.a(deflate.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../../../go/pkg/mod/github.com/4kills/go-zlib@v1.1.0/native/libs/linuxlibz.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

**Comment by 4kills** [comment]
Hi @woshiyyya,

sorry for the delay. The current Linux binaries of the zlib C library are for `amd64`. 
I have added instructions for the compilation process for linux/arm64 [here](https://github.com/4kills/go-zlib/blob/master/README.md#installation-for-a-particular-os-and-architecture). Unfortunately, I don't have the time to compile the zlib library for linux/arm64 by myself but it would be much appreciated if you could contribute the library files to the repository once you have compiled them. 

If you have any further questions, let me know :).
