### ISSUE TITLE
Read() doesn't adhere to io.Reader specifications

### ISSUE THREAD

**Issue by kush789** [4kills/zlib#11]
Hi,

I noticed that Read() does not adhere to the io.Reader specifications;.

The specification says `Read reads up to len(p) bytes into p` ([source](https://pkg.go.dev/io#Reader))
Meanwhile, the library's Read() does the following ([source](https://github.com/4kills/go-zlib/blob/master/reader.go#L64))

```
		min := len(p)
		if len(p) < r.outBuffer.Len() {
			min = r.outBuffer.Len()
		}
		copy(p, r.outBuffer.Bytes()[:min])
```

Consequently, the read could be larger than `len(p)`. 
I'm wondering whether this deviation is deliberate?

Thanks!

**Comment by 4kills** [comment]
You actually found a bug there. The if statement should not use lesser-than but greater-than. I've fixed it in the latest release.
