### ISSUE TITLE
ReadBuffer takes too long if compressed data > 90kb

### ISSUE THREAD

**Issue by zannet** [4kills/zlib#14]
What should I do if I don't know the uncompressed size? ReadBuffer takes too long if compressed data > 90kb with nil out, should I make a big enough out like this:

out := make([]byte, 1000000)
n, _, err := zr.ReadBuffer(message, out)
fmt.Printf("message read: %d, decoded message: %s, err: %v\n", n, out, err)

But how large should I make out? Is there any other method to decompress the data in one go?

edit: ReadBuffer will block if nil out

**Comment by 4kills** [comment]
If your compressed packets are discrete and only slightly larger than the 90kB, your best bet would be to use [go-libdeflate](https://github.com/4kills/go-libdeflate) as it is optimized for these workloads. It is faster and easier to handle and fully zlib-compatible. 

However, if you do not want to switch, make sure you have the latest version of [zlib](https://zlib.net/) installed, as an old version might cause issues, especially if you encounter that blocking behavior. 

If that also doesn't work, you can usually estimate the required size by multiplying the compressed size times your expected compression factor which is rarely higher than 10. E.g.:
```go
compressionFactor := 10 // what you expect at most
out := make([]byte, len(message) * compressionFactor)
```

If that is not enough, you should check the error and if the out buffer was not large enough, you can create a loop that re-tries with larger out buffers. A common choice is to double the `compressionFactor` each try. This should be a last resort, though. Usually it suffices to estimate a compression factor. You then also have to make sure not to exceed a certain number, as this retry approach can quickly reach large numbers. 

I hope this answers this question.
