### ISSUE TITLE
怎么build呢？一直报错，mac win

### ISSUE THREAD

**Issue by onyxio0** [4kills/zlib#4]

**Comment by haveachin** [comment]
Is your environment set up properly? And what exactly is the error message that you are getting?
Note that this library requires GCC to compile properly. See [Prerequisites](https://github.com/4kills/go-zlib#prerequisites) for more details.

**Comment by onyxio0** [comment]
it is now correct.the cross-compilation used before. cross compilation will be wrong. thank you
