### ISSUE TITLE
good libs and wonder if some function equal to zlib.h 's uncompress function

### ISSUE THREAD

**Issue by whidbey** [4kills/zlib#6]
good libs and wonder if some function equal to zlib.h 's uncompress function

**Comment by 4kills** [comment]
Thanks @whidbey . 

Currently there is no such function in this library. However, I've also created bindings for the libdeflate library which improves upon the original zlib in terms of efficiency but uses the same standard. (See [benchmarks](https://github.com/4kills/go-libdeflate#benchmarks) for details).

If you want that function right now have a look at [this](https://github.com/4kills/go-libdeflate) library. 
I recommend that library anyways if you only want to compress data that fits into RAM at once.

**Comment by whidbey** [comment]
ok,thanks.. like the benchmark.
