### ISSUE TITLE
There is no `ReadBytes` method

### ISSUE THREAD

**Issue by gwainor** [4kills/zlib#7]
README.md shows an alternative method for decompressing data using `ReadBytes()` method. Was this method removed?

**Comment by haveachin** [comment]
It looks like it changed from `ReadBytes` to `ReadBuffer` in https://github.com/4kills/go-zlib/commit/c700734e43104c4dfa1cc3128417f03e8a9d1eb9

**Comment by 4kills** [comment]
Thanks for bringing this to my attention. It is fixed in https://github.com/4kills/go-zlib/commit/60b95f4596bddda4d76d1e5b9523ed032c5f378c .
